name: Stephanie Daniels
favicon: null
layout_spectrum: 0.7671470704954118
typography_spectrum: 0.9282091048080474
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3476712729316205
  lightness: 0.9814701478462666
  saturation: 0.32595278695225716
  rhythmicContrast: 0.22997662099078298
purpose: []
